apiVersion: pgcluster.kubesphere.io/v1alpha1
kind: PostgreSQLCluster
metadata:
  name: postgresqlcluster-sample
spec:
  # create user
  action: "create_user"
  clientVersion: "4.7.1"
  namespace: "pgtest"
  clusterName:
    - "test001"
  managedUser: true
  passwordAgeDays: 86400
  passwordLength: 8
  passwordType: "md5"
  username: "mgw"
  password: "123456"


#  todo 是否需要
#  ccpImageTag: ""

