apiVersion: pgcluster.kubesphere.io/v1alpha1
kind: PostgreSQLCluster
metadata:
  name: postgresqlcluster-sample
spec:
  # show user
  action: "show_user"
  clientVersion: "4.7.1"
  namespace: "pgtest"
  clusterName:
    - "test001"
  allFlag: false
  showSystemAccounts: true


