# permissions for end users to edit postgresqlclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresqlcluster-editor-role
rules:
- apiGroups:
  - pgcluster.kubesphere.io
  resources:
  - postgresqlclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pgcluster.kubesphere.io
  resources:
  - postgresqlclusters/status
  verbs:
  - get
