# permissions for end users to view postgresqlclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresqlcluster-viewer-role
rules:
- apiGroups:
  - pgcluster.kubesphere.io
  resources:
  - postgresqlclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pgcluster.kubesphere.io
  resources:
  - postgresqlclusters/status
  verbs:
  - get
