apiVersion: pgcluster.kubesphere.io/v1alpha1
kind: PostgreSQLCluster
metadata:
  name: postgresqlcluster-sample
spec:
  # create cluster
  action: "create_cluster"
  clientVersion: "4.7.1"
  name: "test001"
  namespace: "pgtest"
  syncReplication: true
  ccpImage: ""
  ccpImageTag: ""
  replicaCount: 1
  cpuLimit: "1"
  cpuRequest: "1"
  memoryLimit: "1Gi"
  memoryRequest: "1Gi"
  database: "db1"
  username: "pguser1"
  password: "pass1"

