apiVersion: pgcluster.kubesphere.io/v1alpha1
kind: PostgreSQLCluster
metadata:
  name: pg-test-01
spec:
  name: "test001"
  namespace: "pgtest"
  syncReplication: true
  ccpImage: ""
  ccpImageTag: ""
  replicaCount: 1
  cpuLimit: "500m"
  cpuRequest: "500m"
  memoryLimit: "1Gi"
  memoryRequest: "1Gi"
  database: "db1"
  username: "pguser1"
  password: "pass1"
  pvcSize: "10Gi"

  # restart
  rollingUpdate: true
  restart: true
#  podAnnotation:
#    - podName: "test001-kmfy"
  # delete cluster

  # scale up
  nodeLabel: ""
  serviceType: ""
  storageConfig: ""
  tolerations: []
  # scale down
  replicaName: "test001-kmfy"
  # create user
  managedUser: true
  passwordAgeDays: 86400
  passwordLength: 8
  passwordType: "md5"
#  users:
#    - username: "pgtest"
#      password: "PassWord@"
  # delete user

  # show user
  showSystemAccounts: true
  # update user
  setSystemAccountPassword: false

  # pg params configmap

