apiVersion: pgcluster.kubesphere.io/v1alpha1
kind: PostgreSQLCluster
metadata:
  name: postgresqlcluster-sample
spec:
  # scale cluster
  actoion: "scale_cluster"
  clientVersion: "4.7.1"
  namespace: "pgtest"
  name: "test001"
  ccpImageTag: ""
  nodeLabel: ""
  replicaCount: 2
  serviceType: ""
  storageConfig: ""
  tolerations: []
