apiVersion: pgcluster.kubesphere.io/v1alpha1
kind: PostgreSQLCluster
metadata:
  name: postgresqlcluster-sample
spec:
  namespace: "pgtest"
  name: "test001"
  replicaCount: 2
  storageConfig: ""
  tolerations: []
