apiVersion: pgcluster.kubesphere.io/v1alpha1
kind: PostgreSQLCluster
metadata:
  name: postgresqlcluster-sample
spec:
  # update cluster
  name: "test001"
  namespace: "pgtest"
  cpuLimit: "600m"
  cpuRequest: "600m"
  memoryLimit: "600Mi"
  memoryRequest: "600Mi"
  pvcSize: "10Gi"


